apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myservice3-k8
  name: myservice3-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice3-k8
  template:
    metadata:
      labels:
        app: myservice3-k8
    spec:
      containers:
      - image: vineetshukla644/myrepo_public:myservice2
        imagePullPolicy: Always
        name: myservice3-k8

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice3-k8
  name: myservice3-k8
spec:
  ports:
  - nodePort: 32223
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: myservice3-k8
  type: NodePort